import { FoodAnalysisResponse, FoodItemDetection } from "../types/food";
import { calculateTotals } from "./nutrition";

export interface TrainedFoodEntry {
  id: string;
  name: string;
  category: "Indian" | "Western" | "Asian" | "Breakfast" | "Healthy" | "Fast Food" | "Snack";
  keywords: string[];
  notes: string;
  items: FoodItemDetection[];
}

export const TRAINED_FOOD_DATASET: TrainedFoodEntry[] = [
  {
    id: "chicken_biryani",
    name: "Chicken Dum Biryani",
    category: "Indian",
    keywords: ["biryani", "chicken", "rice", "dum", "pulao", "spiced rice", "indian"],
    notes: "Aromatic basmati rice layered with spiced tender chicken, saffron, and fresh herbs, served with cucumber raita.",
    items: [
      {
        name: "Spiced Chicken Dum Biryani",
        estimated_weight_g: 350,
        servings: 1,
        calories: 590,
        protein_g: 36,
        carbs_g: 74,
        fat_g: 18,
        fiber_g: 3.5,
        sugar_g: 3,
        sodium_mg: 820,
        confidence: 0.96,
      },
      {
        name: "Cooling Cucumber Raita",
        estimated_weight_g: 90,
        servings: 1,
        calories: 58,
        protein_g: 3.2,
        carbs_g: 5.4,
        fat_g: 2.6,
        fiber_g: 0.6,
        sugar_g: 3.8,
        sodium_mg: 160,
        confidence: 0.92,
      },
    ],
  },
  {
    id: "pepperoni_pizza",
    name: "Pepperoni Pizza (2 Slices)",
    category: "Fast Food",
    keywords: ["pizza", "pepperoni", "cheese", "slice", "crust", "italian", "mozzarella"],
    notes: "Hand-tossed crust with rich tomato marinara, whole milk mozzarella, and crispy spiced beef/pork pepperoni.",
    items: [
      {
        name: "Pepperoni Pizza Slices (2)",
        estimated_weight_g: 215,
        servings: 2,
        calories: 580,
        protein_g: 24,
        carbs_g: 64,
        fat_g: 26,
        fiber_g: 3.2,
        sugar_g: 5.6,
        sodium_mg: 1340,
        confidence: 0.97,
      },
      {
        name: "Garlic Herb Dipping Sauce",
        estimated_weight_g: 30,
        servings: 1,
        calories: 120,
        protein_g: 0.5,
        carbs_g: 2.0,
        fat_g: 12.5,
        fiber_g: 0,
        sugar_g: 0.5,
        sodium_mg: 210,
        confidence: 0.88,
      },
    ],
  },
  {
    id: "cheeseburger_fries",
    name: "Cheeseburger & French Fries",
    category: "Fast Food",
    keywords: ["burger", "cheeseburger", "fries", "beef", "patty", "hamburger", "chips"],
    notes: "Grilled beef patty with melted cheddar, crisp lettuce, tomato, pickles, and golden sea-salt fries.",
    items: [
      {
        name: "Classic Cheddar Cheeseburger",
        estimated_weight_g: 220,
        servings: 1,
        calories: 535,
        protein_g: 30,
        carbs_g: 40,
        fat_g: 31,
        fiber_g: 2.4,
        sugar_g: 7,
        sodium_mg: 980,
        confidence: 0.96,
      },
      {
        name: "Crispy Golden French Fries",
        estimated_weight_g: 110,
        servings: 1,
        calories: 340,
        protein_g: 3.8,
        carbs_g: 44,
        fat_g: 16.5,
        fiber_g: 3.8,
        sugar_g: 0.3,
        sodium_mg: 420,
        confidence: 0.94,
      },
    ],
  },
  {
    id: "masala_dosa",
    name: "Crispy Masala Dosa with Chutney & Sambar",
    category: "Indian",
    keywords: ["dosa", "masala dosa", "sambar", "chutney", "south indian", "potato", "crepe"],
    notes: "Golden fermented rice & lentil crepe filled with spiced mustard-seed potato mash, coconut chutney, and vegetable sambar.",
    items: [
      {
        name: "Crispy Potato Masala Dosa",
        estimated_weight_g: 200,
        servings: 1,
        calories: 320,
        protein_g: 6.8,
        carbs_g: 52,
        fat_g: 10,
        fiber_g: 4.2,
        sugar_g: 2.5,
        sodium_mg: 540,
        confidence: 0.97,
      },
      {
        name: "Vegetable Lentil Sambar",
        estimated_weight_g: 150,
        servings: 1,
        calories: 95,
        protein_g: 4.5,
        carbs_g: 15,
        fat_g: 2.2,
        fiber_g: 3.8,
        sugar_g: 3.2,
        sodium_mg: 460,
        confidence: 0.93,
      },
      {
        name: "Fresh Coconut Chutney",
        estimated_weight_g: 50,
        servings: 1,
        calories: 115,
        protein_g: 1.5,
        carbs_g: 3.5,
        fat_g: 11,
        fiber_g: 2.1,
        sugar_g: 1.2,
        sodium_mg: 180,
        confidence: 0.91,
      },
    ],
  },
  {
    id: "grilled_chicken_rice",
    name: "Grilled Chicken Breast with Brown Rice & Broccoli",
    category: "Healthy",
    keywords: ["chicken", "rice", "broccoli", "brown rice", "healthy", "gym", "bodybuilding", "clean"],
    notes: "Lean marinated grilled chicken breast served with steamed brown rice and tender broccoli florets.",
    items: [
      {
        name: "Marinated Grilled Chicken Breast",
        estimated_weight_g: 180,
        servings: 1,
        calories: 295,
        protein_g: 54,
        carbs_g: 0,
        fat_g: 6.5,
        fiber_g: 0,
        sugar_g: 0,
        sodium_mg: 380,
        confidence: 0.98,
      },
      {
        name: "Steamed Long-Grain Brown Rice",
        estimated_weight_g: 160,
        servings: 1,
        calories: 180,
        protein_g: 4.0,
        carbs_g: 38,
        fat_g: 1.5,
        fiber_g: 2.8,
        sugar_g: 0.4,
        sodium_mg: 5,
        confidence: 0.95,
      },
      {
        name: "Steamed Fresh Broccoli Florets",
        estimated_weight_g: 100,
        servings: 1,
        calories: 34,
        protein_g: 2.6,
        carbs_g: 6.8,
        fat_g: 0.4,
        fiber_g: 2.6,
        sugar_g: 1.4,
        sodium_mg: 33,
        confidence: 0.94,
      },
    ],
  },
  {
    id: "salmon_quinoa",
    name: "Pan-Seared Salmon with Quinoa & Asparagus",
    category: "Healthy",
    keywords: ["salmon", "fish", "quinoa", "asparagus", "omega", "keto", "seafood"],
    notes: "Crisp-skinned Atlantic salmon rich in Omega-3 EPA/DHA, accompanied by fluffy tri-color quinoa and charred asparagus spears.",
    items: [
      {
        name: "Pan-Seared Atlantic Salmon",
        estimated_weight_g: 180,
        servings: 1,
        calories: 375,
        protein_g: 40,
        carbs_g: 0,
        fat_g: 23,
        fiber_g: 0,
        sugar_g: 0,
        sodium_mg: 310,
        confidence: 0.96,
      },
      {
        name: "Cooked Tri-Color Quinoa",
        estimated_weight_g: 140,
        servings: 1,
        calories: 170,
        protein_g: 6.0,
        carbs_g: 30,
        fat_g: 2.8,
        fiber_g: 3.9,
        sugar_g: 1.1,
        sodium_mg: 8,
        confidence: 0.93,
      },
      {
        name: "Charred Garlic Asparagus",
        estimated_weight_g: 90,
        servings: 1,
        calories: 38,
        protein_g: 2.4,
        carbs_g: 4.2,
        fat_g: 1.8,
        fiber_g: 2.1,
        sugar_g: 1.5,
        sodium_mg: 95,
        confidence: 0.91,
      },
    ],
  },
  {
    id: "paneer_butter_masala",
    name: "Paneer Butter Masala with 2 Roti",
    category: "Indian",
    keywords: ["paneer", "paneer butter masala", "roti", "chapati", "curry", "cottage cheese", "vegetarian"],
    notes: "Cubes of fresh cottage cheese simmered in a rich, buttery tomato cream gravy with warm whole-wheat rotis.",
    items: [
      {
        name: "Paneer Butter Masala Gravy",
        estimated_weight_g: 220,
        servings: 1,
        calories: 390,
        protein_g: 16,
        carbs_g: 14,
        fat_g: 30,
        fiber_g: 2.8,
        sugar_g: 6.5,
        sodium_mg: 680,
        confidence: 0.95,
      },
      {
        name: "Whole Wheat Tawa Roti (2 pcs)",
        estimated_weight_g: 80,
        servings: 2,
        calories: 210,
        protein_g: 6.4,
        carbs_g: 40,
        fat_g: 2.8,
        fiber_g: 5.2,
        sugar_g: 0.8,
        sodium_mg: 120,
        confidence: 0.96,
      },
    ],
  },
  {
    id: "chicken_curry_rice",
    name: "Home-style Chicken Curry with Steamed Rice & Dal",
    category: "Indian",
    keywords: ["chicken curry", "curry", "rice", "dal", "thali", "indian meal", "white rice"],
    notes: "Tender chicken in caramelized onion-tomato curry, white basmati rice, and yellow lentil dal.",
    items: [
      {
        name: "Steamed White Basmati Rice",
        estimated_weight_g: 200,
        servings: 1,
        calories: 260,
        protein_g: 5.2,
        carbs_g: 57,
        fat_g: 0.5,
        fiber_g: 1.0,
        sugar_g: 0.1,
        sodium_mg: 10,
        confidence: 0.96,
      },
      {
        name: "Homestyle Spiced Chicken Curry",
        estimated_weight_g: 160,
        servings: 1,
        calories: 275,
        protein_g: 28,
        carbs_g: 7.5,
        fat_g: 15,
        fiber_g: 1.8,
        sugar_g: 2.8,
        sodium_mg: 590,
        confidence: 0.94,
      },
      {
        name: "Yellow Dal Tadka",
        estimated_weight_g: 120,
        servings: 1,
        calories: 135,
        protein_g: 8.0,
        carbs_g: 19,
        fat_g: 3.2,
        fiber_g: 4.2,
        sugar_g: 1.2,
        sodium_mg: 420,
        confidence: 0.92,
      },
    ],
  },
  {
    id: "pasta_bolognese",
    name: "Spaghetti Bolognese with Parmesan",
    category: "Western",
    keywords: ["pasta", "spaghetti", "bolognese", "meat sauce", "beef", "italian", "noodles", "parmesan"],
    notes: "Al dente Italian spaghetti topped with slow-simmered beef ragù, sweet Italian basil, and grated aged parmesan.",
    items: [
      {
        name: "Spaghetti with Beef Bolognese Ragù",
        estimated_weight_g: 320,
        servings: 1,
        calories: 520,
        protein_g: 32,
        carbs_g: 68,
        fat_g: 14,
        fiber_g: 4.5,
        sugar_g: 7.2,
        sodium_mg: 740,
        confidence: 0.96,
      },
      {
        name: "Grated Aged Parmesan Cheese",
        estimated_weight_g: 15,
        servings: 1,
        calories: 65,
        protein_g: 5.5,
        carbs_g: 0.5,
        fat_g: 4.5,
        fiber_g: 0,
        sugar_g: 0,
        sodium_mg: 180,
        confidence: 0.90,
      },
    ],
  },
  {
    id: "avocado_toast_eggs",
    name: "Sourdough Avocado Toast with Poached Eggs",
    category: "Breakfast",
    keywords: ["avocado", "toast", "eggs", "poached", "sourdough", "breakfast", "brunch"],
    notes: "Toasted artisan sourdough bread smeared with seasoned Hass avocado, microgreens, and two soft poached eggs.",
    items: [
      {
        name: "Avocado on Artisan Sourdough",
        estimated_weight_g: 160,
        servings: 1,
        calories: 290,
        protein_g: 7.5,
        carbs_g: 32,
        fat_g: 15,
        fiber_g: 6.8,
        sugar_g: 1.8,
        sodium_mg: 310,
        confidence: 0.97,
      },
      {
        name: "Farm Fresh Poached Eggs (2 pcs)",
        estimated_weight_g: 100,
        servings: 2,
        calories: 144,
        protein_g: 12.8,
        carbs_g: 0.8,
        fat_g: 9.8,
        fiber_g: 0,
        sugar_g: 0.4,
        sodium_mg: 142,
        confidence: 0.98,
      },
    ],
  },
  {
    id: "caesar_salad_chicken",
    name: "Grilled Chicken Caesar Salad",
    category: "Healthy",
    keywords: ["salad", "caesar", "chicken salad", "lettuce", "croutons", "parmesan", "greens"],
    notes: "Crisp romaine hearts tossed in creamy garlic dressing, shaved parmesan, garlic croutons, and grilled chicken strips.",
    items: [
      {
        name: "Grilled Herb Chicken Strips",
        estimated_weight_g: 140,
        servings: 1,
        calories: 230,
        protein_g: 42,
        carbs_g: 0.5,
        fat_g: 5.8,
        fiber_g: 0,
        sugar_g: 0,
        sodium_mg: 410,
        confidence: 0.96,
      },
      {
        name: "Romaine Caesar Salad with Croutons",
        estimated_weight_g: 150,
        servings: 1,
        calories: 210,
        protein_g: 5.0,
        carbs_g: 14,
        fat_g: 16,
        fiber_g: 2.8,
        sugar_g: 2.2,
        sodium_mg: 480,
        confidence: 0.94,
      },
    ],
  },
  {
    id: "sushi_roll_platter",
    name: "Salmon & Tuna Sushi Roll (8 pcs)",
    category: "Asian",
    keywords: ["sushi", "salmon sushi", "tuna", "roll", "maki", "japanese", "raw fish"],
    notes: "Fresh Atlantic salmon and yellowfin tuna rolled in seasoned sushi rice, toasted nori, and avocado with pickled ginger.",
    items: [
      {
        name: "Salmon Avocado Maki Roll (4 pcs)",
        estimated_weight_g: 130,
        servings: 4,
        calories: 245,
        protein_g: 11,
        carbs_g: 32,
        fat_g: 8.5,
        fiber_g: 2.2,
        sugar_g: 4.5,
        sodium_mg: 420,
        confidence: 0.95,
      },
      {
        name: "Spicy Tuna Roll (4 pcs)",
        estimated_weight_g: 130,
        servings: 4,
        calories: 260,
        protein_g: 14,
        carbs_g: 30,
        fat_g: 9.8,
        fiber_g: 1.8,
        sugar_g: 4.2,
        sodium_mg: 510,
        confidence: 0.93,
      },
    ],
  },
  {
    id: "burrito_bowl",
    name: "Chipotle-Style Chicken Burrito Bowl",
    category: "Western",
    keywords: ["burrito", "bowl", "chipotle", "mexican", "black beans", "salsa", "guacamole"],
    notes: "Cilantro-lime brown rice, seasoned pinto beans, grilled fajita chicken, roasted corn salsa, and guacamole.",
    items: [
      {
        name: "Grilled Fajita Chicken & Rice",
        estimated_weight_g: 240,
        servings: 1,
        calories: 380,
        protein_g: 38,
        carbs_g: 42,
        fat_g: 7.5,
        fiber_g: 2.5,
        sugar_g: 1.8,
        sodium_mg: 620,
        confidence: 0.96,
      },
      {
        name: "Black Beans & Roasted Corn Salsa",
        estimated_weight_g: 120,
        servings: 1,
        calories: 140,
        protein_g: 6.8,
        carbs_g: 26,
        fat_g: 1.2,
        fiber_g: 6.4,
        sugar_g: 3.5,
        sodium_mg: 380,
        confidence: 0.92,
      },
      {
        name: "Fresh Hand-Smashed Guacamole",
        estimated_weight_g: 60,
        servings: 1,
        calories: 130,
        protein_g: 1.4,
        carbs_g: 6.2,
        fat_g: 12,
        fiber_g: 4.4,
        sugar_g: 0.8,
        sodium_mg: 160,
        confidence: 0.94,
      },
    ],
  },
  {
    id: "oatmeal_berries",
    name: "Steel-Cut Oatmeal with Banana, Berries & Honey",
    category: "Breakfast",
    keywords: ["oatmeal", "oats", "porridge", "banana", "berries", "breakfast", "cereal"],
    notes: "Warm whole-grain rolled oats cooked in almond milk, topped with sliced ripe banana, fresh blueberries, and raw honey.",
    items: [
      {
        name: "Steel-Cut Rolled Oats (in Almond Milk)",
        estimated_weight_g: 240,
        servings: 1,
        calories: 220,
        protein_g: 7.0,
        carbs_g: 40,
        fat_g: 4.2,
        fiber_g: 5.5,
        sugar_g: 2.0,
        sodium_mg: 80,
        confidence: 0.97,
      },
      {
        name: "Sliced Banana & Fresh Blueberries",
        estimated_weight_g: 100,
        servings: 1,
        calories: 95,
        protein_g: 1.1,
        carbs_g: 23,
        fat_g: 0.3,
        fiber_g: 2.8,
        sugar_g: 15,
        sodium_mg: 2,
        confidence: 0.96,
      },
    ],
  },
  {
    id: "steak_mashed_potatoes",
    name: "Grilled Ribeye Steak with Garlic Mashed Potatoes",
    category: "Western",
    keywords: ["steak", "beef", "ribeye", "mashed potatoes", "meat", "dinner"],
    notes: "Cast-iron seared ribeye steak basted with rosemary butter, served alongside buttery garlic russet mashed potatoes.",
    items: [
      {
        name: "Seared Prime Ribeye Steak",
        estimated_weight_g: 220,
        servings: 1,
        calories: 520,
        protein_g: 48,
        carbs_g: 0,
        fat_g: 36,
        fiber_g: 0,
        sugar_g: 0,
        sodium_mg: 460,
        confidence: 0.97,
      },
      {
        name: "Creamy Garlic Mashed Potatoes",
        estimated_weight_g: 160,
        servings: 1,
        calories: 215,
        protein_g: 3.8,
        carbs_g: 32,
        fat_g: 9.0,
        fiber_g: 2.8,
        sugar_g: 2.4,
        sodium_mg: 440,
        confidence: 0.93,
      },
    ],
  },
  {
    id: "fruit_salad_platter",
    name: "Fresh Tropical Fruit Medley Bowl",
    category: "Snack",
    keywords: ["fruit", "fruits", "apple", "banana", "watermelon", "pineapple", "healthy snack"],
    notes: "Chilled diced watermelon, honeydew, sweet pineapple, strawberries, and fresh blueberries.",
    items: [
      {
        name: "Tropical Mixed Fresh Fruit Bowl",
        estimated_weight_g: 280,
        servings: 1,
        calories: 145,
        protein_g: 2.2,
        carbs_g: 36,
        fat_g: 0.6,
        fiber_g: 4.8,
        sugar_g: 28,
        sodium_mg: 6,
        confidence: 0.98,
      },
    ],
  },
];

export function findMatchingFoodEntry(queryOrHint?: string, seedString?: string): FoodAnalysisResponse {
  if (queryOrHint && queryOrHint.trim().length > 1) {
    const q = queryOrHint.toLowerCase().trim();
    const directMatch = TRAINED_FOOD_DATASET.find(
      (entry) =>
        entry.name.toLowerCase().includes(q) ||
        entry.keywords.some((k) => q.includes(k) || k.includes(q))
    );
    if (directMatch) {
      const totals = calculateTotals(directMatch.items);
      return {
        food_items: directMatch.items,
        total: totals,
        notes: directMatch.notes,
      };
    }
  }

  let hash = 0;
  const str = seedString || queryOrHint || "default_food_seed";
  for (let i = 0; i < str.length; i++) {
    hash = (hash << 5) - hash + str.charCodeAt(i);
    hash |= 0;
  }
  const index = Math.abs(hash) % TRAINED_FOOD_DATASET.length;
  const selected = TRAINED_FOOD_DATASET[index];
  const totals = calculateTotals(selected.items);

  return {
    food_items: selected.items,
    total: totals,
    notes: selected.notes,
  };
}

export function searchTrainedFoodEntries(query: string): TrainedFoodEntry[] {
  if (!query.trim()) return TRAINED_FOOD_DATASET.slice(0, 8);
  const q = query.toLowerCase().trim();
  return TRAINED_FOOD_DATASET.filter(
    (e) =>
      e.name.toLowerCase().includes(q) ||
      e.category.toLowerCase().includes(q) ||
      e.keywords.some((k) => k.includes(q))
  );
}
